# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys,res_rc,time

from main import processload
from coba import Ui_MainWindow
counter =0
class Ui_Formloading(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(975, 650)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(100, 230, 381, 221))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e9ecef, stop:1 #6c757d);\n"
"border-radius : 20px;\n"
"border: 5px solid #6c757d;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(40, 30, 400, 400))
        self.frame_6.setStyleSheet("background-color: none;\n"
"border-radius : 200px;\n"
"border: 10px solid #495057;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(340, 140, 251, 261))
        self.frame_2.setStyleSheet("border: 5px solid #212529;\n"
"border-radius : 20px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgb(114, 122, 130), stop:1 #e2e6e9);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(260, 70, 331, 401))
        self.frame_3.setStyleSheet("image: url(:/image/Image/linetracer__-removebg-preview.png);\n"
"backgorund-color:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 400, 221, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#343a40;")
        self.label.setObjectName("label")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(90, 250, 101, 51))
        self.frame_5.setStyleSheet("image: url(:/icon/Icon/arduino-svgrepo-com (1).svg);\n"
"border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(140, 390, 341, 171))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e2e6e9, stop:1 rgb(114, 122, 130));\n"
"border-radius:50px;\n"
"border:10px solid #495057;\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.progressBar = QtWidgets.QProgressBar(self.frame_4)
        self.progressBar.setGeometry(QtCore.QRect(50, 120, 241, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #6c757d, stop:1 #e9ecef);\n"
"color:#343a40;\n"
"border-style:none;\n"
"border-radius:10px;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 #6c757d, stop:0 #e9ecef);\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(490, 150, 221, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#343a40;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(490, 305, 221, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#343a40;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(520, 180, 221, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#343a40;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(493, 335, 221, 51))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#343a40;")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(206, 490, 201, 21))
        font = QtGui.QFont()
        font.setFamily("BankGothic Md BT")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#343a40;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.label.raise_()
        self.frame_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.timer = QtCore.QTimer()
        self.timer.start(35)

        self.label_7.setText("Initialize")

        QtCore.QTimer.singleShot(1500,lambda:self.label_7.setText("Loading Database"))
        QtCore.QTimer.singleShot(3000,lambda:self.label_7.setText("Get Ready"))
        
        def progress():
            global counter
            processload(self,counter,Form)
            self.progressBar.setValue(counter)
            if counter>100:
                self.timer.stop() 
            counter+=1  
        self.timer.timeout.connect(progress)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "WELCOME"))
        self.label_2.setText(_translate("Form", "AR"))
        self.label_3.setText(_translate("Form", "TRA"))
        self.label_4.setText(_translate("Form", "DU"))
        self.label_5.setText(_translate("Form", "CER"))
        self.label_7.setText(_translate("Form", "Initialize"))
         
    def mainwi(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window1)
        self.window1.show()
                
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Formloading()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
